# Prometheus configuration for EU-USA Data Pipeline monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'data-pipeline'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  - job_name: 'data-pipeline-staging'
    static_configs:
      - targets: ['data-pipelines-staging.deno.dev']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: https
    
  - job_name: 'data-pipeline-production'
    static_configs:
      - targets: ['data-pipelines-prod.deno.dev']
    metrics_path: '/metrics' 
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: https

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'blackbox'
    static_configs:
      - targets:
        - 'https://data-pipelines-prod.deno.dev/health'
        - 'https://data-pipelines-staging.deno.dev/health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115